//
// AWSConfiguration.h
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.6
//
#import <AWSCore/AWSCore.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:7bb22b6c-100b-4fdf-94c8-5f349ae63096"
// USER AGENT
#define AWS_MOBILEHUB_USER_AGENT @"MobileHub 383f6a0d-14be-4cd5-9c46-e3a3b2062a6f aws-my-sample-app-ios-objc-v0.6"
